pull_request_rules:
- actions:
    merge:
      method: merge
  conditions:
  - author=dependabot[bot]
  - check-success*=ci/hydra:ironfetch:*:aarch64-linux.hydra-spec
  - check-success*=ci/hydra:ironfetch:*:aarch64-linux.ironfetch
  - check-success*=ci/hydra:ironfetch:*:aarch64-linux.ironfetch-clippy
  - check-success*=ci/hydra:ironfetch:*:aarch64-linux.ironfetch-deny
  - check-success*=ci/hydra:ironfetch:*:aarch64-linux.ironfetch-fmt
  - check-success*=ci/hydra:ironfetch:*:aarch64-linux.mergify-check
  - check-success*=ci/hydra:ironfetch:*:aarch64-linux.pre-commit-check
  - check-success*=ci/hydra:ironfetch:*:x86_64-linux.hydra-spec
  - check-success*=ci/hydra:ironfetch:*:x86_64-linux.ironfetch
  - check-success*=ci/hydra:ironfetch:*:x86_64-linux.ironfetch-clippy
  - check-success*=ci/hydra:ironfetch:*:x86_64-linux.ironfetch-deny
  - check-success*=ci/hydra:ironfetch:*:x86_64-linux.ironfetch-fmt
  - check-success*=ci/hydra:ironfetch:*:x86_64-linux.mergify-check
  - check-success*=ci/hydra:ironfetch:*:x86_64-linux.pre-commit-check
  name: Automatically merge dependabot updates
