[package]
name = "ironfetch"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "*", features = ["derive"] }
colored = "*"
measurements = "*"
nix = "*"
os-release = "*"
procfs = "*"
smbios-lib = "0.9.0"
sys-info = "*"
uptime_lib = "*"

[build-dependencies]
clap = { version = "*", features = ["derive"] }
clap_complete = "*"
clap_mangen = "*"
