[package]
name = "ironfetch"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
measurements = "0.11.0"
nix = "0.26.2"
os-release = "0.1.0"
procfs = "0.15.1"
sys-info = "0.9.1"
uptime_lib = "0.2.2"

[build-dependencies]
clap = { version = "4.1.8", features = ["derive"] }
clap_complete = "4.3.1"
