[package]
name = "ironfetch"
version = "0.3.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "*", features = ["derive"] }
colored = "*"
measurements = "*"
nix = { version="*", features = ["feature"]}
os-release = "*"
procfs = "*"
sys-info = "*"
uptime_lib = "*"
simplesmbios = { git = "https://github.com/Lyndeno/simplesmbios-rust" }

[[bin]]
name = "ironfetch"
path = "src/main.rs"
doc = false

[lib]
name = "ironfetch"
path = "src/lib.rs"

[build-dependencies]
clap = { version = "*", features = ["derive"] }
clap_complete = "*"
clap_mangen = "*"

[lints.clippy]
pedantic = {level="warn", priority = 0}
must_use_candidate = "allow"
unwrap_used = {level="warn", priority = 2}
stable_sort_primitive = {level="allow", priority = 1}
