name: Check Flake

on:
  pull_request:

  workflow_dispatch:

  workflow_call:

  push:
    branches:
    - master

jobs:
  nix-build:
    name: Check Ironfetch
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: DeterminateSystems/magic-nix-cache-action@v13
      - run: nix run github:Mic92/nix-fast-build -- --no-nom --skip-cached --result-file results.xml --result-format junit
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: (!cancelled())
        with:
          files: |
            test-results/**/*.xml
            test-results/**/*.trx
            test-results/**/*.json
